name: CD

on:
  push:
    branches:
      - 'master'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm ci --force

      - name: Build
        run: npm run build

      - name: Publish
        run: npm run publish




